version: '3'
services:
  web:
    build: .
    ports:
      - "8090:80"
    depends_on:
      - connect-mysql
    networks:
      - atende

  connect-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Ncm@647534
    networks:
      - atende

networks:
  atende:
    driver: bridge
